### PR TITLE
Added badges

### PR DESCRIPTION
**Pull request by assertchris**
Once you've set up Travis and Scrutinizer support; these will begin to work. Like magic! :)

### CODE REVIEW

**Comment by HallofFamer** [comment]
Okay sounds good. I am trying to add this repo to Scrutinizer now, and something confuses it. It asks 'Should Scrutinizer run your tests?' in a checkbox. Do you recommend me to check or uncheck it?

**Comment by assertchris** [comment]
Leave that unchecked. Travis will run the tests (it's much better at that) and send coverage data to Scrutinizer. It's all set up [like that] as far as the configs go.

**Comment by HallofFamer** [comment]
I see, I already did and it seems to be working properly. For Travis though, I am having a bit of confusion here. I tried to add github repo for PCF to Travis, and it's been loading like this for a very long time:
http://oi60.tinypic.com/2qrzk08.jpg

I dunno if this is a normal behavior or I may have done something wrong?

**Comment by assertchris** [comment]
Did you add the web-hook (like the instructions suggested). If so; it might just be waiting for a first commit since adding to Travis...

**Comment by HallofFamer** [comment]
Yeah I think so. is this a problem?

**Comment by assertchris** [comment]
Nope. I think everything's on track!

**Comment by HallofFamer** [comment]
Okay thats good, so I can merge this pull request too?

**Comment by assertchris** [comment]
Yes, go ahead. We can always fix if things aren't connecting properly.

**Comment by HallofFamer** [comment]
alright, will do.

**Comment by assertchris** [comment]
Working nicely!

screen shot 2015-02-01 at 10 56 11 pm

Please don't approve any patches from Scrutinizer. They're not always the best way to fix the issues, but I will work on the issues as I write tests. Thanks for the help in setting it up!

**Comment by HallofFamer** [comment]
I understand, I will be careful with anything Scrutinizer brings up. Thanks for notifying me.

**Pull request merged**
